// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOD6l13jOAQVtcqg3fY9P_Sy4YgD0e4T4',
    appId: '1:236576797870:web:beb87df98cecc2b856293f',
    messagingSenderId: '236576797870',
    projectId: 'skype-clone-cb7b3',
    authDomain: 'skype-clone-cb7b3.firebaseapp.com',
    databaseURL: 'https://skype-clone-cb7b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skype-clone-cb7b3.appspot.com',
    measurementId: 'G-QEK5YY248P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoMFLBQmnvCzUxKD10KouDThoTfltqY4U',
    appId: '1:236576797870:android:90c1ee7fdb54850d56293f',
    messagingSenderId: '236576797870',
    projectId: 'skype-clone-cb7b3',
    databaseURL: 'https://skype-clone-cb7b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skype-clone-cb7b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsMrNRqOG7ZjwZsSf1i3mvtZ8oEbS6Ok',
    appId: '1:236576797870:ios:cd8af7db3736c8ee56293f',
    messagingSenderId: '236576797870',
    projectId: 'skype-clone-cb7b3',
    databaseURL: 'https://skype-clone-cb7b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skype-clone-cb7b3.appspot.com',
    androidClientId: '236576797870-hgc60abdesl80k3n7ffcn4ec5bb1j16l.apps.googleusercontent.com',
    iosClientId: '236576797870-o5q1i0ikpc2ckbdqcs6on7f5mud3vr16.apps.googleusercontent.com',
    iosBundleId: 'com.example.skypeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsMrNRqOG7ZjwZsSf1i3mvtZ8oEbS6Ok',
    appId: '1:236576797870:ios:cd8af7db3736c8ee56293f',
    messagingSenderId: '236576797870',
    projectId: 'skype-clone-cb7b3',
    databaseURL: 'https://skype-clone-cb7b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skype-clone-cb7b3.appspot.com',
    androidClientId: '236576797870-hgc60abdesl80k3n7ffcn4ec5bb1j16l.apps.googleusercontent.com',
    iosClientId: '236576797870-o5q1i0ikpc2ckbdqcs6on7f5mud3vr16.apps.googleusercontent.com',
    iosBundleId: 'com.example.skypeClone',
  );
}
